[project]
name = "archive_processing"
version = "1.0.1"
requires-python = ">=3.12"
dependencies = [
    "astropy",
    "boto3<1.36.0",
    "botocore<1.36.0",
    "moto",
    "psycopg"
]

[dependency-groups]
dev = ["pytest"]
